
[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002&"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002d"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002H"
key = "Left"
mods = "Command|Option"

[[keyboard.bindings]]
chars = "\u0002J"
key = "Down"
mods = "Command|Option"

[[keyboard.bindings]]
chars = "\u0002K"
key = "Up"
mods = "Command|Option"

[[keyboard.bindings]]
chars = "\u0002L"
key = "Right"
mods = "Command|Option"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\f"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Option"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Option"

[general]
live_config_reload = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = false
opacity = 0.8
startup_mode = "Maximized"
title = "Rocks or Sucks"

[window.dimensions]
columns = 0
lines = 0

[keyboard]

[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "source ~/.zshrc && tmux attach || tmux"]
# args = ["-l", "-c", "tmux attach || tmux"]

